prometheus:
  port: 8080
  endpoint: /metrics

communication:
  consumer_url: "http://localhost:8081/consume"

task_production:
  max_backlog: 100
  message_rate: 5 # 2 tasks per second

logging:
  level: "info" # Choose between: debug, info, warn, error
  format: "console" # "console" or "json"

profiling:
  port: 6060

database:
  source: "postgres://postgres:baha123@localhost:5432/taskdb?sslmode=disable"

# New metrics for tracking tasks produced
metrics:
  tasks_produced_total: 0 # Total tasks produced