prometheus:
  port: 8081
  endpoint: /metrics

communication:
  consumer_url: "http://localhost:8081/consume"

task_consumption:
  message_rate: 1 # 1 task per second
  burst_limit: 5 # Allow burst of 5 tasks

logging:
  level: "info" # Choose between: debug, info, warn, error
  format: "console" # "console" or "json"

profiling:
  port: 6060

database:
  source: "postgres://postgres:baha123@localhost:5432/taskdb?sslmode=disable"

# New metrics for tracking tasks processed
metrics:
  tasks_processed_total: 0 # Total tasks processed
  tasks_done_total: 0       # Total tasks done
  tasks_per_type:           # Counts per task type
    type_0: 0
    type_1: 0
    type_2: 0
    type_3: 0
    type_4: 0
    type_5: 0
    type_6: 0
    type_7: 0
    type_8: 0
    type_9: 0
  total_value_per_type:     # Total value per task type
    type_0: 0
    type_1: 0
    type_2: 0
    type_3: 0
    type_4: 0
    type_5: 0
    type_6: 0
    type_7: 0
    type_8: 0
    type_9: 0
