global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'producer'
    static_configs:
      - targets: ['producer:8080']  # Change this to the correct address and port

  - job_name: 'consumer'
    static_configs:
      - targets: ['consumer:8081']  # Change this to the correct address and port


