// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Task struct {
	ID             int32
	Type           int32
	Value          int32
	State          string
	CreationTime   sql.NullTime
	LastUpdateTime sql.NullTime
}
