# config/consumer/config.yaml
prometheus:
  port: 8081
  endpoint: "/metrics"

communication:
  service1_url: "http://localhost:8080/"
  protocol: "http"

logging:
  level: "info"
  format: "console"

profiling:
  port: 7070

message_consumption:
  rate: 100

database:
  connection_url: "postgres://postgres:baha123@localhost:5432/taskdb?sslmode=disable"
